services:
  api:
    container_name: evo_api
    image: jcca993/evolution_api_custom:latest
    restart: always
    networks:
      - internal
    depends_on:
      - redis
    ports:
      - 9094:8080
    volumes:
      - ./data/api:/evolution/instances
    env_file:
      - .env
#    expose:
#      - 8080

  redis:
    container_name: redis_evo
    image: redis:latest
    networks:
      - internal
    command: redis-server /usr/local/etc/redis/redis.conf
    #ports:
     #- 6379:6379
    volumes:
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
networks:
  internal: